# CMake generated Testfile for 
# Source directory: /home/spatchava/embeddedos-org/eNI/tests
# Build directory: /home/spatchava/embeddedos-org/eNI/build-linux/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(eni_common_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_common")
set_tests_properties(eni_common_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;8;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_min_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_min")
set_tests_properties(eni_min_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;14;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_framework_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_framework")
set_tests_properties(eni_framework_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;20;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_provider_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_providers")
set_tests_properties(eni_provider_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;26;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_event_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_event")
set_tests_properties(eni_event_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;33;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_policy_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_policy")
set_tests_properties(eni_policy_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;40;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_neuralink_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_neuralink")
set_tests_properties(eni_neuralink_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;47;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_filter_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_filter")
set_tests_properties(eni_filter_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;54;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_normalizer_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_normalizer")
set_tests_properties(eni_normalizer_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;61;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_event_feedback_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_event_feedback")
set_tests_properties(eni_event_feedback_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;70;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_provider_eeg_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_provider_eeg")
set_tests_properties(eni_provider_eeg_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;77;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_fw_decoder_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_fw_decoder")
set_tests_properties(eni_fw_decoder_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;92;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_fw_feedback_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_fw_feedback")
set_tests_properties(eni_fw_feedback_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;100;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_config_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_config_extended")
set_tests_properties(eni_config_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;107;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_stream_bus_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_stream_bus_extended")
set_tests_properties(eni_stream_bus_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;117;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_stim_safety_coverage_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_stim_safety_coverage")
set_tests_properties(eni_stim_safety_coverage_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;124;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_platform_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_platform_extended")
set_tests_properties(eni_platform_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;135;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_dsp_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_dsp")
set_tests_properties(eni_dsp_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;145;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_nn_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_nn")
set_tests_properties(eni_nn_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;156;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_decoder_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_decoder")
set_tests_properties(eni_decoder_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;167;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_stimulator_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_stimulator")
set_tests_properties(eni_stimulator_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;175;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_stim_safety_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_stim_safety")
set_tests_properties(eni_stim_safety_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;183;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_bci_pipeline_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_bci_pipeline")
set_tests_properties(eni_bci_pipeline_tests PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;194;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_dsp_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_dsp_extended")
set_tests_properties(eni_dsp_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;217;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_nn_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_nn_extended")
set_tests_properties(eni_nn_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;228;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_decoder_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_decoder_extended")
set_tests_properties(eni_decoder_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;239;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_provider_lifecycle_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_provider_lifecycle")
set_tests_properties(eni_provider_lifecycle_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;246;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_stim_safety_extended_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_stim_safety_extended")
set_tests_properties(eni_stim_safety_extended_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;253;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_full_pipeline_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_full_pipeline")
set_tests_properties(eni_full_pipeline_tests PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;264;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_json_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_json")
set_tests_properties(eni_json_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;275;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_thread_safety_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_thread_safety")
set_tests_properties(eni_thread_safety_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;285;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_data_format_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_data_formats")
set_tests_properties(eni_data_format_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;295;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_session_calibration_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_session_calibration")
set_tests_properties(eni_session_calibration_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;306;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_types_coverage_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_types_coverage")
set_tests_properties(eni_types_coverage_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;317;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_log_coverage_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_log_coverage")
set_tests_properties(eni_log_coverage_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;323;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_event_coverage_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_event_coverage")
set_tests_properties(eni_event_coverage_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;329;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_policy_coverage_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_policy_coverage")
set_tests_properties(eni_policy_coverage_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;335;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_calibration_session_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_calibration_session")
set_tests_properties(eni_calibration_session_tests PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;353;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_mini_session_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_mini_session")
set_tests_properties(eni_mini_session_tests PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;374;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
add_test(eni_concurrent_stress_tests "/home/spatchava/embeddedos-org/eNI/build-linux/tests/eni_test_concurrent_stress")
set_tests_properties(eni_concurrent_stress_tests PROPERTIES  LABELS "stress" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;393;add_test;/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
