# CMake generated Testfile for 
# Source directory: C:/home/spatchava/embeddedos-org/eNI/tests
# Build directory: C:/home/spatchava/embeddedos-org/eNI/build-test/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_common_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_common.exe")
  set_tests_properties([=[eni_common_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;8;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_common_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_common.exe")
  set_tests_properties([=[eni_common_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;8;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_common_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_common.exe")
  set_tests_properties([=[eni_common_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;8;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_common_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_common.exe")
  set_tests_properties([=[eni_common_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;8;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_common_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_min_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_min.exe")
  set_tests_properties([=[eni_min_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;14;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_min_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_min.exe")
  set_tests_properties([=[eni_min_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;14;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_min_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_min.exe")
  set_tests_properties([=[eni_min_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;14;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_min_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_min.exe")
  set_tests_properties([=[eni_min_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;14;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_min_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_framework_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_framework.exe")
  set_tests_properties([=[eni_framework_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;20;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_framework_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_framework.exe")
  set_tests_properties([=[eni_framework_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;20;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_framework_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_framework.exe")
  set_tests_properties([=[eni_framework_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;20;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_framework_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_framework.exe")
  set_tests_properties([=[eni_framework_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;20;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_framework_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_provider_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_providers.exe")
  set_tests_properties([=[eni_provider_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;26;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_provider_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_providers.exe")
  set_tests_properties([=[eni_provider_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;26;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_provider_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_providers.exe")
  set_tests_properties([=[eni_provider_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;26;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_provider_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_providers.exe")
  set_tests_properties([=[eni_provider_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;26;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_provider_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_event_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_event.exe")
  set_tests_properties([=[eni_event_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;33;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_event_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_event.exe")
  set_tests_properties([=[eni_event_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;33;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_event_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_event.exe")
  set_tests_properties([=[eni_event_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;33;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_event_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_event.exe")
  set_tests_properties([=[eni_event_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;33;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_event_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_policy_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_policy.exe")
  set_tests_properties([=[eni_policy_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;40;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_policy_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_policy.exe")
  set_tests_properties([=[eni_policy_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;40;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_policy_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_policy.exe")
  set_tests_properties([=[eni_policy_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;40;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_policy_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_policy.exe")
  set_tests_properties([=[eni_policy_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;40;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_policy_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_neuralink_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_neuralink.exe")
  set_tests_properties([=[eni_neuralink_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;47;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_neuralink_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_neuralink.exe")
  set_tests_properties([=[eni_neuralink_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;47;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_neuralink_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_neuralink.exe")
  set_tests_properties([=[eni_neuralink_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;47;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_neuralink_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_neuralink.exe")
  set_tests_properties([=[eni_neuralink_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;47;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_neuralink_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_filter_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_filter.exe")
  set_tests_properties([=[eni_filter_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;54;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_filter_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_filter.exe")
  set_tests_properties([=[eni_filter_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;54;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_filter_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_filter.exe")
  set_tests_properties([=[eni_filter_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;54;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_filter_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_filter.exe")
  set_tests_properties([=[eni_filter_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;54;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_filter_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_normalizer_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_normalizer.exe")
  set_tests_properties([=[eni_normalizer_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;61;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_normalizer_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_normalizer.exe")
  set_tests_properties([=[eni_normalizer_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;61;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_normalizer_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_normalizer.exe")
  set_tests_properties([=[eni_normalizer_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;61;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_normalizer_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_normalizer.exe")
  set_tests_properties([=[eni_normalizer_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;61;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_normalizer_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_event_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_event_feedback.exe")
  set_tests_properties([=[eni_event_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;70;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_event_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_event_feedback.exe")
  set_tests_properties([=[eni_event_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;70;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_event_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_event_feedback.exe")
  set_tests_properties([=[eni_event_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;70;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_event_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_event_feedback.exe")
  set_tests_properties([=[eni_event_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;70;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_event_feedback_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_provider_eeg_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_provider_eeg.exe")
  set_tests_properties([=[eni_provider_eeg_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;77;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_provider_eeg_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_provider_eeg.exe")
  set_tests_properties([=[eni_provider_eeg_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;77;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_provider_eeg_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_provider_eeg.exe")
  set_tests_properties([=[eni_provider_eeg_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;77;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_provider_eeg_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_provider_eeg.exe")
  set_tests_properties([=[eni_provider_eeg_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;77;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_provider_eeg_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_fw_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_fw_decoder.exe")
  set_tests_properties([=[eni_fw_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;92;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_fw_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_fw_decoder.exe")
  set_tests_properties([=[eni_fw_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;92;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_fw_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_fw_decoder.exe")
  set_tests_properties([=[eni_fw_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;92;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_fw_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_fw_decoder.exe")
  set_tests_properties([=[eni_fw_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;92;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_fw_decoder_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_fw_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_fw_feedback.exe")
  set_tests_properties([=[eni_fw_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;100;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_fw_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_fw_feedback.exe")
  set_tests_properties([=[eni_fw_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;100;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_fw_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_fw_feedback.exe")
  set_tests_properties([=[eni_fw_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;100;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_fw_feedback_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_fw_feedback.exe")
  set_tests_properties([=[eni_fw_feedback_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;100;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_fw_feedback_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_config_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_config_extended.exe")
  set_tests_properties([=[eni_config_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;107;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_config_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_config_extended.exe")
  set_tests_properties([=[eni_config_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;107;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_config_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_config_extended.exe")
  set_tests_properties([=[eni_config_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;107;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_config_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_config_extended.exe")
  set_tests_properties([=[eni_config_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;107;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_config_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_stream_bus_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_stream_bus_extended.exe")
  set_tests_properties([=[eni_stream_bus_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;117;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_stream_bus_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_stream_bus_extended.exe")
  set_tests_properties([=[eni_stream_bus_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;117;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_stream_bus_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_stream_bus_extended.exe")
  set_tests_properties([=[eni_stream_bus_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;117;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_stream_bus_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_stream_bus_extended.exe")
  set_tests_properties([=[eni_stream_bus_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;117;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_stream_bus_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_stim_safety_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_stim_safety_coverage.exe")
  set_tests_properties([=[eni_stim_safety_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;124;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_stim_safety_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_stim_safety_coverage.exe")
  set_tests_properties([=[eni_stim_safety_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;124;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_stim_safety_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_stim_safety_coverage.exe")
  set_tests_properties([=[eni_stim_safety_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;124;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_stim_safety_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_stim_safety_coverage.exe")
  set_tests_properties([=[eni_stim_safety_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;124;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_stim_safety_coverage_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_platform_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_platform_extended.exe")
  set_tests_properties([=[eni_platform_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;135;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_platform_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_platform_extended.exe")
  set_tests_properties([=[eni_platform_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;135;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_platform_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_platform_extended.exe")
  set_tests_properties([=[eni_platform_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;135;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_platform_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_platform_extended.exe")
  set_tests_properties([=[eni_platform_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;135;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_platform_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_dsp_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_dsp.exe")
  set_tests_properties([=[eni_dsp_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;145;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_dsp_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_dsp.exe")
  set_tests_properties([=[eni_dsp_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;145;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_dsp_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_dsp.exe")
  set_tests_properties([=[eni_dsp_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;145;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_dsp_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_dsp.exe")
  set_tests_properties([=[eni_dsp_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;145;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_dsp_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_nn_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_nn.exe")
  set_tests_properties([=[eni_nn_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;156;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_nn_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_nn.exe")
  set_tests_properties([=[eni_nn_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;156;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_nn_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_nn.exe")
  set_tests_properties([=[eni_nn_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;156;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_nn_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_nn.exe")
  set_tests_properties([=[eni_nn_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;156;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_nn_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_decoder.exe")
  set_tests_properties([=[eni_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;167;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_decoder.exe")
  set_tests_properties([=[eni_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;167;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_decoder.exe")
  set_tests_properties([=[eni_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;167;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_decoder_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_decoder.exe")
  set_tests_properties([=[eni_decoder_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;167;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_decoder_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_stimulator_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_stimulator.exe")
  set_tests_properties([=[eni_stimulator_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;175;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_stimulator_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_stimulator.exe")
  set_tests_properties([=[eni_stimulator_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;175;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_stimulator_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_stimulator.exe")
  set_tests_properties([=[eni_stimulator_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;175;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_stimulator_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_stimulator.exe")
  set_tests_properties([=[eni_stimulator_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;175;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_stimulator_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_stim_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_stim_safety.exe")
  set_tests_properties([=[eni_stim_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;183;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_stim_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_stim_safety.exe")
  set_tests_properties([=[eni_stim_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;183;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_stim_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_stim_safety.exe")
  set_tests_properties([=[eni_stim_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;183;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_stim_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_stim_safety.exe")
  set_tests_properties([=[eni_stim_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;183;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_stim_safety_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_bci_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_bci_pipeline.exe")
  set_tests_properties([=[eni_bci_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;194;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_bci_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_bci_pipeline.exe")
  set_tests_properties([=[eni_bci_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;194;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_bci_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_bci_pipeline.exe")
  set_tests_properties([=[eni_bci_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;194;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_bci_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_bci_pipeline.exe")
  set_tests_properties([=[eni_bci_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;194;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_bci_pipeline_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_dsp_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_dsp_extended.exe")
  set_tests_properties([=[eni_dsp_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;217;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_dsp_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_dsp_extended.exe")
  set_tests_properties([=[eni_dsp_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;217;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_dsp_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_dsp_extended.exe")
  set_tests_properties([=[eni_dsp_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;217;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_dsp_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_dsp_extended.exe")
  set_tests_properties([=[eni_dsp_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;217;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_dsp_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_nn_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_nn_extended.exe")
  set_tests_properties([=[eni_nn_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;228;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_nn_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_nn_extended.exe")
  set_tests_properties([=[eni_nn_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;228;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_nn_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_nn_extended.exe")
  set_tests_properties([=[eni_nn_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;228;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_nn_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_nn_extended.exe")
  set_tests_properties([=[eni_nn_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;228;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_nn_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_decoder_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_decoder_extended.exe")
  set_tests_properties([=[eni_decoder_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;239;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_decoder_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_decoder_extended.exe")
  set_tests_properties([=[eni_decoder_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;239;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_decoder_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_decoder_extended.exe")
  set_tests_properties([=[eni_decoder_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;239;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_decoder_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_decoder_extended.exe")
  set_tests_properties([=[eni_decoder_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;239;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_decoder_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_provider_lifecycle_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_provider_lifecycle.exe")
  set_tests_properties([=[eni_provider_lifecycle_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;246;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_provider_lifecycle_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_provider_lifecycle.exe")
  set_tests_properties([=[eni_provider_lifecycle_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;246;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_provider_lifecycle_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_provider_lifecycle.exe")
  set_tests_properties([=[eni_provider_lifecycle_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;246;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_provider_lifecycle_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_provider_lifecycle.exe")
  set_tests_properties([=[eni_provider_lifecycle_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;246;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_provider_lifecycle_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_stim_safety_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_stim_safety_extended.exe")
  set_tests_properties([=[eni_stim_safety_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;253;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_stim_safety_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_stim_safety_extended.exe")
  set_tests_properties([=[eni_stim_safety_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;253;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_stim_safety_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_stim_safety_extended.exe")
  set_tests_properties([=[eni_stim_safety_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;253;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_stim_safety_extended_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_stim_safety_extended.exe")
  set_tests_properties([=[eni_stim_safety_extended_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;253;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_stim_safety_extended_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_full_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_full_pipeline.exe")
  set_tests_properties([=[eni_full_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;264;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_full_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_full_pipeline.exe")
  set_tests_properties([=[eni_full_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;264;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_full_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_full_pipeline.exe")
  set_tests_properties([=[eni_full_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;264;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_full_pipeline_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_full_pipeline.exe")
  set_tests_properties([=[eni_full_pipeline_tests]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;264;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_full_pipeline_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_json_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_json.exe")
  set_tests_properties([=[eni_json_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;275;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_json_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_json.exe")
  set_tests_properties([=[eni_json_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;275;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_json_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_json.exe")
  set_tests_properties([=[eni_json_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;275;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_json_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_json.exe")
  set_tests_properties([=[eni_json_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;275;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_json_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_thread_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_thread_safety.exe")
  set_tests_properties([=[eni_thread_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;285;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_thread_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_thread_safety.exe")
  set_tests_properties([=[eni_thread_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;285;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_thread_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_thread_safety.exe")
  set_tests_properties([=[eni_thread_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;285;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_thread_safety_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_thread_safety.exe")
  set_tests_properties([=[eni_thread_safety_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;285;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_thread_safety_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_data_format_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_data_formats.exe")
  set_tests_properties([=[eni_data_format_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;295;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_data_format_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_data_formats.exe")
  set_tests_properties([=[eni_data_format_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;295;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_data_format_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_data_formats.exe")
  set_tests_properties([=[eni_data_format_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;295;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_data_format_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_data_formats.exe")
  set_tests_properties([=[eni_data_format_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;295;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_data_format_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_session_calibration_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_session_calibration.exe")
  set_tests_properties([=[eni_session_calibration_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;306;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_session_calibration_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_session_calibration.exe")
  set_tests_properties([=[eni_session_calibration_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;306;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_session_calibration_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_session_calibration.exe")
  set_tests_properties([=[eni_session_calibration_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;306;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_session_calibration_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_session_calibration.exe")
  set_tests_properties([=[eni_session_calibration_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;306;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_session_calibration_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_types_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_types_coverage.exe")
  set_tests_properties([=[eni_types_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;317;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_types_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_types_coverage.exe")
  set_tests_properties([=[eni_types_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;317;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_types_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_types_coverage.exe")
  set_tests_properties([=[eni_types_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;317;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_types_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_types_coverage.exe")
  set_tests_properties([=[eni_types_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;317;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_types_coverage_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_log_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_log_coverage.exe")
  set_tests_properties([=[eni_log_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;323;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_log_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_log_coverage.exe")
  set_tests_properties([=[eni_log_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;323;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_log_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_log_coverage.exe")
  set_tests_properties([=[eni_log_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;323;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_log_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_log_coverage.exe")
  set_tests_properties([=[eni_log_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;323;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_log_coverage_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_event_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_event_coverage.exe")
  set_tests_properties([=[eni_event_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;329;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_event_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_event_coverage.exe")
  set_tests_properties([=[eni_event_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;329;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_event_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_event_coverage.exe")
  set_tests_properties([=[eni_event_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;329;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_event_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_event_coverage.exe")
  set_tests_properties([=[eni_event_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;329;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_event_coverage_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_policy_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_policy_coverage.exe")
  set_tests_properties([=[eni_policy_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;335;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_policy_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_policy_coverage.exe")
  set_tests_properties([=[eni_policy_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;335;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_policy_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_policy_coverage.exe")
  set_tests_properties([=[eni_policy_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;335;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_policy_coverage_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_policy_coverage.exe")
  set_tests_properties([=[eni_policy_coverage_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;335;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_policy_coverage_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_calibration_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_calibration_session.exe")
  set_tests_properties([=[eni_calibration_session_tests]=] PROPERTIES  DISABLED "TRUE" LABELS "integration" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;353;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_calibration_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_calibration_session.exe")
  set_tests_properties([=[eni_calibration_session_tests]=] PROPERTIES  DISABLED "TRUE" LABELS "integration" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;353;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_calibration_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_calibration_session.exe")
  set_tests_properties([=[eni_calibration_session_tests]=] PROPERTIES  DISABLED "TRUE" LABELS "integration" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;353;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_calibration_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_calibration_session.exe")
  set_tests_properties([=[eni_calibration_session_tests]=] PROPERTIES  DISABLED "TRUE" LABELS "integration" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;353;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_calibration_session_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_mini_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_mini_session.exe")
  set_tests_properties([=[eni_mini_session_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;374;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_mini_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_mini_session.exe")
  set_tests_properties([=[eni_mini_session_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;374;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_mini_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_mini_session.exe")
  set_tests_properties([=[eni_mini_session_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;374;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_mini_session_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_mini_session.exe")
  set_tests_properties([=[eni_mini_session_tests]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;374;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_mini_session_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[eni_concurrent_stress_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Debug/eni_test_concurrent_stress.exe")
  set_tests_properties([=[eni_concurrent_stress_tests]=] PROPERTIES  LABELS "stress" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;393;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[eni_concurrent_stress_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/Release/eni_test_concurrent_stress.exe")
  set_tests_properties([=[eni_concurrent_stress_tests]=] PROPERTIES  LABELS "stress" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;393;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[eni_concurrent_stress_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/MinSizeRel/eni_test_concurrent_stress.exe")
  set_tests_properties([=[eni_concurrent_stress_tests]=] PROPERTIES  LABELS "stress" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;393;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[eni_concurrent_stress_tests]=] "C:/home/spatchava/embeddedos-org/eNI/build-test/tests/RelWithDebInfo/eni_test_concurrent_stress.exe")
  set_tests_properties([=[eni_concurrent_stress_tests]=] PROPERTIES  LABELS "stress" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;393;add_test;C:/home/spatchava/embeddedos-org/eNI/tests/CMakeLists.txt;0;")
else()
  add_test([=[eni_concurrent_stress_tests]=] NOT_AVAILABLE)
endif()
