# Sanitizer build configurations
option(ENI_ENABLE_ASAN  "Enable AddressSanitizer"           OFF)
option(ENI_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ENI_ENABLE_TSAN  "Enable ThreadSanitizer"            OFF)
option(ENI_ENABLE_MSAN  "Enable MemorySanitizer"            OFF)

if(ENI_ENABLE_ASAN)
    add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
    add_link_options(-fsanitize=address)
    message(STATUS "AddressSanitizer enabled")
endif()

if(ENI_ENABLE_UBSAN)
    add_compile_options(-fsanitize=undefined -fno-omit-frame-pointer)
    add_link_options(-fsanitize=undefined)
    message(STATUS "UndefinedBehaviorSanitizer enabled")
endif()

if(ENI_ENABLE_TSAN)
    if(ENI_ENABLE_ASAN)
        message(FATAL_ERROR "TSAN and ASAN cannot be used simultaneously")
    endif()
    add_compile_options(-fsanitize=thread)
    add_link_options(-fsanitize=thread)
    message(STATUS "ThreadSanitizer enabled")
endif()

if(ENI_ENABLE_MSAN)
    if(ENI_ENABLE_ASAN OR ENI_ENABLE_TSAN)
        message(FATAL_ERROR "MSAN cannot be used with ASAN or TSAN")
    endif()
    add_compile_options(-fsanitize=memory -fno-omit-frame-pointer)
    add_link_options(-fsanitize=memory)
    message(STATUS "MemorySanitizer enabled")
endif()
